"""The About page's project links (antenna_plugin.links + its section), off
KiCad.

Two questions, and both are about honesty rather than layout: does the list of
links stay well-formed (a label, a name and an absolute URL per row, so the
section can render whatever is added there), and would the section admit a
placeholder address -- a link added before its destination is published --
instead of offering it as a working one.

The section is built on the wx stand-in (tests/wx_stub), so what is checked is
what it put in the box -- the row labels, the link names and the tooltips --
not how wx would lay it out.

    python3 tests/test_links.py
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wx_stub  # noqa: F401,E402  (installs the stand-in wx)
from bare_package import load, run_module_tests  # noqa: E402

links = load("links")
links_section = load("gui.sections.links")

wx = wx_stub.wx


class _Page:
    """Just what a Section reads off its page."""

    def __init__(self):
        self.scroll = object()
        self.wrapped = []

    def register_wrap(self, label):
        self.wrapped.append(label)

    def _relayout_scroll(self):
        pass


def test_entries_are_named_absolute_urls():
    rows = links.entries()
    assert [row.name for row in rows] == ["GitHub", "Discord"]
    for row in rows:
        assert row.label and row.name
        assert row.url.startswith("https://"), row.url


def test_both_urls_are_published_addresses():
    """Both destinations exist, so nothing offered here may be a stand-in --
    add a link before its destination is published and it goes under
    PLACEHOLDER_HOST, which is what the section's note keys off."""
    assert not any(links.is_placeholder(row.url) for row in links.entries())
    assert links.is_placeholder(links.PLACEHOLDER_HOST + "chat")


def test_the_result_pages_are_signed_with_the_published_address():
    """Every page the plugin shows a result in says who made it, and points at
    the repository links.py names -- never a second copy of the address. The
    pages are the shipped viewer's (antenna_plugin/viewer/), so this is what
    catches a copy taken from upstream with a different project's signature on
    it."""
    viewer = pathlib.Path(__file__).resolve().parents[1] / "antenna_plugin" / "viewer"
    pages = sorted(viewer.glob("*.html"))
    assert [p.name for p in pages] == ["grid.html", "report.html"]
    for page in pages:
        text = page.read_text(encoding="utf-8")
        assert text.count('<div class="credit">Generated by ') == 1
        assert links.GITHUB_URL in text
        # ...with the way to reach it from a file:// page that may refuse to
        # follow the click.
        assert "<small>(right click to copy link)</small>" in text


def test_the_section_offers_a_row_per_link():
    body = wx.BoxSizer()
    section = links_section.LinksSection(_Page(), body)
    labels = _labels(body)
    for row in links.entries():
        assert row.label in labels, row.label
        assert row.name in labels, row.name
    assert section._entries == links.entries()


def test_a_published_link_is_offered_plainly():
    """Nothing is a stand-in today: the tooltip is the bare URL and the box
    carries no note about placeholders."""
    body = wx.BoxSizer()
    links_section.LinksSection(_Page(), body)
    tips = [w.tooltip for w in _flatten(body) if getattr(w, "tooltip", "")]
    for row in links.entries():
        assert row.url in tips, row.url
    assert not any("placeholder" in label for label in _labels(body))


def test_a_placeholder_link_says_so_on_the_row_and_once_for_the_box():
    """A link added before its destination is published: the URL is still on
    the tooltip (it is what a user copies out), but it is not offered as if it
    worked."""
    pending = links.Link("Handbook", "Docs", links.PLACEHOLDER_HOST + "docs")
    page = _Page()
    body = wx.BoxSizer()
    original = links.entries
    links.entries = lambda: original() + [pending]
    try:
        links_section.LinksSection(page, body)
    finally:
        links.entries = original
    tips = [w.tooltip for w in _flatten(body) if getattr(w, "tooltip", "")]
    assert any(pending.url in tip and "placeholder" in tip for tip in tips)
    assert any("placeholder" in label for label in _labels(body))
    assert page.wrapped, "the note wraps with the window"


def _flatten(sizer):
    """Every widget under ``sizer``, its nested sizers walked through."""
    out = []
    for item in sizer.items:
        if isinstance(item, wx.BoxSizer):  # every stand-in sizer is this class
            out.extend(_flatten(item))
        else:
            out.append(item)
    return out


def _labels(sizer):
    return [w.GetLabel() for w in _flatten(sizer)]


if __name__ == "__main__":
    run_module_tests(globals())
