"""The About page's project links (emkit.links + its section) and the feedback
box under them, off KiCad.

Two questions, and both are about honesty rather than layout: does the list of
links stay well-formed (a label, a name and an absolute URL per row, so the
section can render whatever is added there), and would the section admit a
placeholder address -- a link added before its destination is published --
instead of offering it as a working one. The feedback box adds a third: does it
still ask for the report, and does its one link go to the tracker.

The section is built on the wx stand-in (tests/wx_stub), so what is checked is
what it put in the box -- the row labels, the link names and the tooltips --
not how wx would lay it out.

    python3 tests/test_links.py
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wx_stub  # noqa: F401,E402  (installs the stand-in wx)
from bare_package import CORE, PRODUCT, load, run_module_tests  # noqa: E402

links = load("emkit.links")
links_section = load("emkit.gui.sections.links")
feedback_section = load("emkit.gui.sections.feedback")

wx = wx_stub.wx


class _Page:
    """Just what a Section reads off its page."""

    def __init__(self):
        self.scroll = object()
        self.wrapped = []

    def register_wrap(self, label):
        self.wrapped.append(label)

    def _relayout_scroll(self):
        pass


def test_entries_are_named_absolute_urls():
    rows = links.entries()
    assert [row.name for row in rows] == [
        "automaticphysics.com",
        "GitHub",
        "Discord",
    ]
    assert links.ISSUES_URL.startswith(links.GITHUB_URL)
    for row in rows:
        assert row.label and row.name
        assert row.url.startswith("https://"), row.url


def test_both_urls_are_published_addresses():
    """Both destinations exist, so nothing offered here may be a stand-in --
    add a link before its destination is published and it goes under
    PLACEHOLDER_HOST, which is what the section's note keys off."""
    assert not any(links.is_placeholder(row.url) for row in links.entries())
    assert links.is_placeholder(links.PLACEHOLDER_HOST + "chat")


# The repository each result page is signed with. Deliberately *not*
# links.GITHUB_URL: the pages are the simulator's own viewer (emkit/viewer/),
# shipped unchanged, so a page names the flow that wrote the dump rather than
# the plugin that happens to be running. A page only one flow produces says so
# outright; the grid, which both produce, picks at load time off the dump it
# read -- so the assertion there is that it does the picking, and js/grid.js
# holds the URLs. Changing any of this is a change in ems/.
#
# Every page the *core* carries is listed; an install holds the subset
# tools/assemble.stage_viewer left it -- see below.
VIEWER_CREDITS = {
    "report.html": "https://github.com/admin-2026/kicad_ems_plugin_pub",
    "scattering.html": "https://github.com/admin-2026/kicad_si_plugin_pub",
    "grid.html": None,  # per dump, from js/grid.js
}

# What this product ships of that: its own result page, plus the grid every
# flow writes.
SHIPPED_PAGES = sorted({"grid.html", PRODUCT.REPORT_PAGE})


def test_the_result_pages_are_signed_with_the_published_address():
    """Every page a result is shown in says who made it, and points at a
    repository of this project -- never a second copy of the address. This is
    what catches a copy taken from upstream with somebody else's signature on
    it."""
    viewer = CORE / "viewer"
    pages = sorted(viewer.glob("*.html"))
    assert [p.name for p in pages] == SHIPPED_PAGES
    for page in pages:
        text = page.read_text(encoding="utf-8")
        assert text.count('<div class="credit">Generated by ') == 1
        expected = VIEWER_CREDITS[page.name]
        if expected:
            assert expected in text
        # ...with the way to reach it from a file:// page that may refuse to
        # follow the click.
        assert "<small>(right click to copy link)</small>" in text


def test_another_products_result_page_is_not_installed():
    """A page this flow never writes the data for would still be copied into
    the user's board directory (sim.simulate.install_viewer copies the folder
    whole), and its credit line points at another product's repository. So it
    is not here: assembly drops it, with the script it loads."""
    viewer = CORE / "viewer"
    for page in VIEWER_CREDITS:
        if page in SHIPPED_PAGES:
            continue
        assert not (viewer / page).exists(), page
        assert not (viewer / "js" / f"{page[:-5]}.js").exists(), page


def test_the_shared_page_credits_whichever_flow_wrote_the_dump():
    """grid.html is drawn for both products, so its signature cannot be in the
    HTML: js/grid.js rewrites it from the dump that answered, and every
    address it can choose is one of this project's."""
    script = (CORE / "viewer" / "js" / "grid.js").read_text(encoding="utf-8")
    assert ".credit a" in script
    assert "https://github.com/admin-2026/kicad_${p}_plugin_pub" in script
    # The two it can name, and the dump name that tells them apart.
    assert "'si' : 'ems'" in script
    assert "/scattering/" in script


def test_the_section_offers_a_row_per_link():
    body = wx.BoxSizer()
    section = links_section.LinksSection(_Page(), body)
    labels = _labels(body)
    for row in links.entries():
        assert row.label in labels, row.label
        assert row.name in labels, row.name
    assert section._entries == links.entries()


def test_the_feedback_box_asks_for_reports_and_offers_the_tracker():
    """The section below the links: it asks for bugs and features, points at
    the chat for the rest, and the one link it offers is the issue tracker."""
    page = _Page()
    body = wx.BoxSizer()
    feedback_section.FeedbackSection(page, body)
    note = "\n".join(_labels(body))
    for word in ("bug", "feature", "versions", "Discord"):
        assert word in note, word
    tips = [w.tooltip for w in _flatten(body) if getattr(w, "tooltip", "")]
    assert tips == [links.ISSUES_URL]
    assert page.wrapped, "the note wraps with the window"


def test_a_published_link_is_offered_plainly():
    """Nothing is a stand-in today: the tooltip is the bare URL and the box
    carries no note about placeholders."""
    body = wx.BoxSizer()
    links_section.LinksSection(_Page(), body)
    tips = [w.tooltip for w in _flatten(body) if getattr(w, "tooltip", "")]
    for row in links.entries():
        assert row.url in tips, row.url
    assert not any("placeholder" in label for label in _labels(body))


def test_a_placeholder_link_says_so_on_the_row_and_once_for_the_box():
    """A link added before its destination is published: the URL is still on
    the tooltip (it is what a user copies out), but it is not offered as if it
    worked."""
    pending = links.Link("Handbook", "Docs", links.PLACEHOLDER_HOST + "docs")
    page = _Page()
    body = wx.BoxSizer()
    original = links.entries
    links.entries = lambda: original() + [pending]
    try:
        links_section.LinksSection(page, body)
    finally:
        links.entries = original
    tips = [w.tooltip for w in _flatten(body) if getattr(w, "tooltip", "")]
    assert any(pending.url in tip and "placeholder" in tip for tip in tips)
    assert any("placeholder" in label for label in _labels(body))
    assert page.wrapped, "the note wraps with the window"


def _flatten(sizer):
    """Every widget under ``sizer``, its nested sizers walked through."""
    out = []
    for item in sizer.items:
        if isinstance(item, wx.BoxSizer):  # every stand-in sizer is this class
            out.extend(_flatten(item))
        else:
            out.append(item)
    return out


def _labels(sizer):
    return [w.GetLabel() for w in _flatten(sizer)]


if __name__ == "__main__":
    run_module_tests(globals())
