"""Turn a solved candidate into a KiCad footprint, and put it on the board.

The last step of every wizard, and the same for all of them: the winning
:class:`~.geometry.Geometry` becomes a ``.kicad_mod`` -- one SMD pad per
connection point the design declares (the feed for all of them, plus the
ground pin for an inverted-F), with the whole radiator carried by the feed pad
as its custom-shape primitives -- which is written into the project's own
``antenna.pretty`` library and loaded onto the board through pcbnew's
footprint loader, so the board gets exactly what the file says and the user
keeps a reusable library part.

**Why the copper is a pad and not a drawing.** It used to be filled ``fp_poly``
graphics on F.Cu, which look identical on screen and plot identically -- but a
copper *graphic* carries no net, so KiCad's DRC treats it as a foreign copper
island: the moment a track reaches the pad it touches, the clearance test fires
("Clearance violation ... to graphic item") and the router refuses to finish
the connection. Copper that belongs to a pad carries the pad's net, so the
antenna is now one custom pad anchored at the feed and the track lands on it
like on any other pad. An inverted-F pays for that with a second problem:
its ground pin is DC-shorted to the feed through the arm, which is a short
between two nets, so a design with more than one pad also declares a
``net_tie_pad_groups`` -- KiCad 7+'s way of saying the short is deliberate.

The footprint's origin is the design's feed point, which is where the wizard
places it: the point on the area edge the scan simulated the port at. The
copper is emitted *without* the ground/feed stubs the simulation adds, since
on the real board the user's own feed line and pour connect at the pads.

It also carries **what it was generated from** -- the design, the plugin
version, the target frequency and every geometry knob -- as text on F.Fab.
That is annotation.py's business entirely, reached from one line of ``sexpr``
below; the copper does not depend on it.

The s-expression is KiCad 6 syntax (version 20211014), the oldest format every
supported KiCad still parses; its shared pieces (numbers, text items) come
from kicad/modtext.py. (``net_tie_pad_groups`` is a KiCad 7 token in a file
that claims to be older, which is fine on every host the plugin supports --
KiCad 9 upwards -- because the parser reads tokens as it meets them and never
checks them against the declared version.) Everything above the "Board-facing"
divider is pure text generation; ``place`` imports pcbnew lazily like the
markers package.
"""

import os

from .. import product
from ..emkit.kicad.modtext import fp_text, num
from . import annotation


def item_name(design, f0_ghz, total_mm):
    """Library item name for a generated antenna, e.g.
    ``L_Monopole_2G45_23p6mm`` (no dots -- they separate lib from item in a
    LIB_ID). The prefix is the design's (``footprint_prefix``), so two designs
    can never collide in the shared library."""
    f = f"{f0_ghz:g}".replace(".", "G")
    return f"{design.footprint_prefix}_{f}_{total_mm:.1f}mm".replace(".", "p")


# --------------------------------------------------------------------------- #
# The footprint
# --------------------------------------------------------------------------- #
def sexpr(design, geo, values, f0_ghz):
    """The solved candidate as .kicad_mod text: the design's pads
    (``design.footprint_pads``) with the radiator carried by the first of them
    as custom-shape primitives, all in a local frame whose origin is the feed
    point, and the ``values`` it was solved from written on F.Fab
    (annotation.py).

    ``values`` is the design's geometry knobs in mm -- the same dict
    ``design.solve`` was handed for ``geo``, which is also where the track
    width comes from (``design.WIDTH_KEY``): the pads are the width of the
    trace they terminate, so there is no second place to state it."""
    (fx, fy) = geo.feed
    name = item_name(design, f0_ghz, geo.total_mm)
    trace_w_mm = values[design.WIDTH_KEY]
    # Exactly the track width, square: a pad wider than the antenna is a step
    # of copper at the port the simulation never saw, and a narrower one is a
    # neck the antenna's own current has to squeeze through. Either way what
    # the board ends up with is not the geometry that was scanned, so the pad
    # is the same width as the trace it terminates -- no floor, no padding.
    pad = trace_w_mm
    pads = design.footprint_pads(geo)
    lines = [
        f'(footprint "{name}" (version 20211014) (generator {product.PACKAGE})',
        '  (layer "F.Cu")',
        f'  (descr "{design.name}, {round(geo.total_mm, 2):g} mm for '
        f"{f0_ghz:g} GHz, "
        'generated by the Antenna Designer wizard")',
        "  (attr smd exclude_from_pos_files exclude_from_bom)",
    ]
    lines += _net_tie(pads)
    lines += [
        fp_text("reference", "AE**", (0, pad + 1)),
        fp_text("value", name, (0, pad + 2.2), hide=True),
    ]
    # The one line the parameter record costs this module: what it says, how
    # it stacks and how it reads back are annotation.py's, and deleting this
    # leaves the same copper.
    lines += annotation.fab_text(design, values, f0_ghz, below_mm=pad + 2.2)
    # The radiator rides on the first pad -- the feed, for every design. It is
    # one connected blob of copper (each segment overlaps the next by a
    # half-width, and the feed stub starts at the feed point), so it also
    # satisfies what a custom pad demands: every primitive connected to the
    # anchor. A second pad sits inside that blob and needs no copper of its own.
    body = geo.copper_rects(trace_w_mm, 0.0, include_stub=False)
    for i, (number, point) in enumerate(pads):
        lines += _pad(number, point, (fx, fy), pad, body if i == 0 else ())
    lines.append(")")
    return "\n".join(lines) + "\n"


def _net_tie(pads):
    """The ``net_tie_pad_groups`` line for a design with more than one pad, and
    nothing for a single-pad one (a monopole shorts nothing).

    An inverted-F's ground pin and its feed are one piece of copper -- that is
    what makes it an inverted-F -- so once the copper carries a net, KiCad sees
    two nets shorted inside the footprint and DRC says so, over and over, for
    the pour and for every track that reaches either pin. Declaring both pads
    as one net-tie group is the answer KiCad provides for exactly this: the
    short is intended, so the clearance and connectivity tests skip collisions
    that happen inside the tie's own pads."""
    if len(pads) < 2:
        return []
    return ['  (net_tie_pad_groups "{}")'.format(", ".join(n for n, _pt in pads))]


def _pad(number, point, origin, size, rects=()):
    """One SMD pad on F.Cu at ``point`` (solved frame; ``origin`` is the
    footprint's, i.e. the feed) as .kicad_mod lines: a plain square of ``size``
    on its own, or a custom-shape pad whose primitives are ``rects`` when it is
    handed the radiator.

    Two details in the custom case earn their tokens: ``(clearance outline)``
    measures DRC clearance from the copper actually drawn rather than from a
    convex hull around it, which for a meandered arm is the difference between
    a keepout the shape of the antenna and one the shape of its bounding box;
    and the primitives are written relative to the pad, not to the footprint
    origin, because that is the frame KiCad reads them in.

    ``(zone_connect 2)`` -- solid, no thermal spokes -- goes on every pad: the
    scan measured a pin sitting in unbroken copper, and a ground pin joined to
    the pour by four thin spokes is a different antenna."""
    px, py = point
    ox, oy = origin
    at = f"(at {num(px - ox)} {num(py - oy)})"
    head = (
        f'  (pad "{number}" smd {"custom" if rects else "rect"} {at} '
        f'(size {num(size)} {num(size)}) (layers "F.Cu") (zone_connect 2)'
    )
    if not rects:
        return [head + ")"]
    lines = [
        head,
        "    (options (clearance outline) (anchor rect))",
        "    (primitives",
    ]
    for x0, y0, x1, y1 in rects:
        pts = ((x0, y0), (x1, y0), (x1, y1), (x0, y1))
        xy = " ".join(f"(xy {num(x - px)} {num(y - py)})" for x, y in pts)
        lines.append(f"      (gr_poly (pts {xy}) (width 0) (fill solid))")
    lines.append("    ))")
    return lines


# --------------------------------------------------------------------------- #
# Board-facing: footprint placement (lazy pcbnew)
# --------------------------------------------------------------------------- #
def place(board, text, name, at_mm, lib_dir, rot_deg=0.0):
    """Add a generated antenna footprint to the board at ``at_mm`` (the feed
    point, KiCad mm). ``rot_deg`` is the area marker's off-grid rotation (the
    frame the footprint was solved in, mathematically CCW in KiCad's Y-down
    coordinates -- KiCad's own orientation degrees run the other way, hence
    the sign flip). The .kicad_mod ``text`` is written into
    ``lib_dir``/antenna.pretty and loaded through pcbnew's own footprint
    loader, so the board gets exactly what the file says (and the user keeps
    a reusable library). Returns the .kicad_mod path."""
    import pcbnew

    from ..emkit.kicad.compat import vec2

    pretty = os.path.join(str(lib_dir), "antenna.pretty")
    os.makedirs(pretty, exist_ok=True)
    path = os.path.join(pretty, f"{name}.kicad_mod")
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    fp = pcbnew.FootprintLoad(pretty, name)
    if fp is None:
        raise RuntimeError(f"could not load the generated footprint {path}")
    board.Add(fp)
    fp.SetPosition(vec2(pcbnew.FromMM(at_mm[0]), pcbnew.FromMM(at_mm[1])))
    if rot_deg:
        fp.SetOrientationDegrees(-rot_deg)
    pcbnew.Refresh()
    return path
